# This CRD allows us to configure Vault Audit Policy.
# Currently, only file-based auditing is enabled.
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: vaultfileaudits.configuration.vault.krish7919.github.com
  labels:
    app: vault-controller
spec:
  group: configuration.vault.krish7919.github.com
  versions:
  - name: v1
    served: true
    storage: true
  scope: Namespaced
  names:
    kind: VaultFileAudit
    singular: vaultfileaudit
    plural: vaultfileaudits
    shortNames:
    - vfa
  additionalPrinterColumns:
  - name: Age
    type: date
    description: Age
    JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      type: object
      required:
      - spec
      properties:
        spec:
          type: object
          required:
          - filePath
          properties:
            filePath:
              type: string
